env:
  global:
    - CC_TEST_REPORTER_ID=f4c6979c40052fdc70c9ec712fe23f6c0a1fd0c52f2373a5b84334e92e25ddbd
language: node_js
services:
  - mongodb

jobs:
  include:
    - stage: test
      node_js: "node"
      os: linux
      before_script: 
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - chmod +x ./script/copy-custom-definitions.js
        - npm run build || exit 1
        - sleep 5
        - ./cc-test-reporter before-build
      after_success: 
        - 'cat ./coverage/lcov.info | coveralls'
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - stage: platform-test
      node_js: "lts/carbon"
      os: linux
      before_script: sleep 5

install:
  - yarn install

script:
  - npm run test